### ISSUE TITLE
adding param to dap script

### ISSUE THREAD

**Issue by tdlowden** [18F/federalist-uswds-template#14]
hi, I was hoping to submit a PR to add a parameter in the DAP `<script>` that would signify anyone using this template would be using Federalist as a platform. unfortunately, I can only find the includes in the `config.yml` file, and not the place where the `<script>` actually lives. 

I'd like to add `&siteplatform=federalist` after `agency=[AGENCY]` in the script source.

**Comment by line47** [comment]
Hey @tdlowden so the script would read something like this?
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&siteplatform=federalist"></script>

```

**Comment by tdlowden** [comment]
yep! exactly

**Comment by line47** [comment]
I think we could just override the way the scripts.html file is working for federalist templates within this repo 👍
