### ISSUE TITLE
add an "edit this page" button

### ISSUE THREAD

**Issue by davidewarren** [18F/federalist-uswds-template#2]
add an "edit this page" button to the base template that links to the current page markdown file in edit mode.

**Comment by davidewarren** [comment]
I can't figure out how to add an "edit this page" file path with jekyll navigation to the footer because the footer in this template is a .yml rather than an .html

**Comment by line47** [comment]
Hey @davidewarren can you add add a PR on the [uswds-jekyll repo](https://github.com/18F/uswds-jekyll/) for this and close this issue in this repo?

**Comment by line47** [comment]
Added https://github.com/18F/uswds-jekyll/issues/75 and will be closing this issue
