### ISSUE TITLE
Update the USWDS Template to be standalone

### ISSUE THREAD

**Issue by wslack** [18F/federalist-uswds-template#4]
This is talking about having a USWDS Federalist template that had all the things as well as one that only had a place for pages and did not contain all the things.

- [ ] Fold in CSS and source info into the repo
- [ ] Beta test with someone like Jay Huie to ensure usablility: CC @thecapacity

**Comment by wslack** [comment]
@line47 to update this issue

**Comment by line47** [comment]
Will be using the https://github.com/18F/federalist-uswds-template repo to explore these possibilities.

**Comment by line47** [comment]
If we wanted a template that had all the things we should set up [uswds-jekyll](https://github.com/18F/fuswds-jekyll) to be a template that would have everything included (kitchen sink template)

In addition, this repo https://github.com/18F/federalist-uswds-template is the one that would only have the necessary items to update the site (data files, pages, config, assets)

**Comment by wslack** [comment]
I think we should make https://github.com/18f/federalist/issues/1262 contingent on resolving this path, which would clear up this issue.

**Comment by line47** [comment]
I believe this is done.
- the uswds-jekyll would be what is used to have all of the things
- the federalist-uswds-template (master) is what is used to just have pages, styles, and configs

The uswds-jekyll is not an option when you create a new site, if we want to offer that as an option we would need to add that to the current offering. 

CC @wslack
